version: "3.1"

services:
    nginx:
        image: nginx:stable-alpine
        container_name: 1103-nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - 1103-network

    mysql:
        image: mysql:8.0
        container_name: 1103-mysql
        restart: unless-stopped
        ports:
            - 33006:3306
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "1103events" # importante que tengan comillas
            MYSQL_USER: "1103events"
            MYSQL_PASSWORD: "1103events.pass"
            MYSQL_ROOT_PASSWORD: "root.pass"
            MYSQL_ROOT_HOST: "%"
        command: "--default-authentication-plugin=mysql_native_password"
        networks:
            - 1103-network

    php: # 3er servicio
        image: ghcr.io/bjvalmaseda92/laravel-devenv:v1.3.2
        container_name: 1103-php
        restart: unless-stopped #
        volumes: # carpeta de proyecto local : carpeta del container que da vida a los archivos PHP
            - ./:/var/www/html
        ports:
            - 6001:6001
        networks:
            - 1103-network # red
        expose:
            - 9000
networks: # declaracion de la red
    1103-network:

volumes:
    dbdata:
